"""TextEdit's Save sheet. Generated by `python -m macuitest.locators capture`, then edited."""

from macuitest.lib.applescript_lib.applescript_wrapper import as_wrapper
from macuitest.lib.elements.applescript_element import Button as ScriptButton
from macuitest.lib.elements.locators import Screen
from macuitest.lib.elements.locators import applescript
from macuitest.lib.elements.locators import ax
from macuitest.lib.elements.locators import text
from macuitest.lib.elements.native_element import Button
from macuitest.lib.elements.native_element import TextField

# System Events nests the sheet's controls in a splitter group.
SHEET = "splitter group 1 of sheet 1 of window 1"


# The sheet sits inside the document window, so the screen needs no window=.
class SaveSheet(Screen, app="TextEdit"):
    name_field = ax(identifier="saveAsNameTextField", kind=TextField)
    cancel = ax(identifier="CancelButton", kind=Button)
    save = ax(identifier="OKButton", kind=Button)
    # OCR searches the whole document window, sheet included.
    save_as_label = text("Save As:")
    cancel_as = applescript(f'button "Cancel" of {SHEET}', kind=ScriptButton)


def front_window_name() -> str:
    """Return the title of TextEdit's front window, which changes once a document is saved."""
    return as_wrapper.tell_app("TextEdit", "get name of front window")
