"""TextEdit's document window, Save sheet, and Fonts panel.

Generated by `macuitest capture`, then edited.
"""

from macuitest.lib.applescript_lib.applescript_wrapper import as_wrapper
from macuitest.lib.elements.applescript_element import Button as ScriptButton
from macuitest.lib.elements.locators import Screen
from macuitest.lib.elements.locators import applescript
from macuitest.lib.elements.locators import ax
from macuitest.lib.elements.locators import text
from macuitest.lib.elements.locators import window
from macuitest.lib.elements.native_element import Button
from macuitest.lib.elements.native_element import TextField

# System Events nests the sheet's controls in a splitter group.
SHEET = "splitter group 1 of sheet 1 of window 1"


# The sheet sits inside the document window, so the screen needs no window=.
class SaveSheet(Screen, app="TextEdit"):
    name_field = ax(identifier="saveAsNameTextField", kind=TextField)
    cancel = ax(identifier="CancelButton", kind=Button)
    save = ax(identifier="OKButton", kind=Button)
    # OCR searches the whole document window, sheet included.
    save_as_label = text("Save As:")
    cancel_as = applescript(f'button "Cancel" of {SHEET}', kind=ScriptButton)


class TextEdit(Screen, app="TextEdit"):
    # Found in the document window's title bar, outside the Fonts panel.
    untitled = text("Untitled")


# A floating panel: name its window once, and every lookup below searches only that window.
class Fonts(Screen, app="TextEdit", window=window(title="Fonts")):
    collections = ax(identifier="font_collections_picker")
    size = ax(identifier="font_size_picker")
    search = ax(description="Search", role="AXButton", kind=Button)
    typography = ax(description="Typography Panel", role="AXButton", kind=Button)
    # Capture also generated an image() for every font row. The rows change with the selected
    # font, so their entries and screenshots are gone.

    # TextEdit's default font. The document window shows it too, but OCR here reads only the panel.
    helvetica = text("Helvetica")
    untitled = text("Untitled")


def front_window_name() -> str:
    """Return the title of TextEdit's front window, which changes once a document is saved."""
    return as_wrapper.tell_app("TextEdit", "get name of front window")
