"""Calculator's main window. Generated by `macuitest capture`, then edited."""

from macuitest.lib.elements.applescript_element import Button as ScriptButton
from macuitest.lib.elements.locators import Screen
from macuitest.lib.elements.locators import applescript
from macuitest.lib.elements.locators import ax
from macuitest.lib.elements.locators import image
from macuitest.lib.elements.locators import text
from macuitest.lib.elements.native_element import Button

KEYPAD = "group 1 of group 1 of splitter group 1 of group 1 of window 1"


def key(identifier: str) -> str:
    """Return the AppleScript locator of the keypad key with `identifier`."""
    # System Events reads these SwiftUI keys' name as missing value, their description as
    # "button", and can't read AXDescription at all. AXIdentifier is the attribute it can match.
    return f'(first button whose value of attribute "AXIdentifier" is "{identifier}") of {KEYPAD}'


class Calculator(Screen, app="Calculator"):
    keypad = ax(identifier="CalculatorKeypadView")
    input_view = ax(identifier="StandardInputView")
    # The display text has no identifier of its own. It sits inside the input view.
    display = ax(identifier="StandardInputView").child(role="AXStaticText")
    # The generated identifier encodes the current mode, so match the description instead.
    mode = ax(description="Mode", role="AXButton", kind=Button)

    # Generated: every key, by accessibility identifier.
    delete = ax(identifier="Delete", kind=Button)
    all_clear = ax(identifier="AllClear", kind=Button)
    percent = ax(identifier="Percent", kind=Button)
    divide = ax(identifier="Divide", kind=Button)
    seven = ax(identifier="Seven", kind=Button)
    eight = ax(identifier="Eight", kind=Button)
    nine = ax(identifier="Nine", kind=Button)
    multiply = ax(identifier="Multiply", kind=Button)
    four = ax(identifier="Four", kind=Button)
    five = ax(identifier="Five", kind=Button)
    six = ax(identifier="Six", kind=Button)
    subtract = ax(identifier="Subtract", kind=Button)
    one = ax(identifier="One", kind=Button)
    two = ax(identifier="Two", kind=Button)
    three = ax(identifier="Three", kind=Button)
    add = ax(identifier="Add", kind=Button)
    negate = ax(identifier="Negate", kind=Button)
    zero = ax(identifier="Zero", kind=Button)
    decimal = ax(identifier="Decimal", kind=Button)
    equals = ax(identifier="Equals", kind=Button)

    # The same keys by screenshot, reusing the PNGs capture saved for them.
    seven_image = image("seven")
    six_image = image("six")
    multiply_image = image("multiply")
    equals_image = image("equals")

    # The same keys through System Events.
    seven_as = applescript(key("Seven"), kind=ScriptButton)
    six_as = applescript(key("Six"), kind=ScriptButton)
    multiply_as = applescript(key("Multiply"), kind=ScriptButton)
    equals_as = applescript(key("Equals"), kind=ScriptButton)

    # Vision reads "AC" but not single characters, so only multi-letter labels use text().
    all_clear_text = text("AC", within=keypad)
    # A result to wait for, read by Vision. The input view leaves room around the digits.
    result = text("42", within=input_view)


def display_value() -> str:
    """Return the number on Calculator's display, without its left-to-right mark."""
    return str(Calculator.display.value).lstrip("\u200e")
